import { deleteLocalPhotoDurably, getLocalPhotoMetadataRepository, type LocalPhotoMetadataRepository } from "./local-photo.ts";
import { getNativeLocalSubmission } from "./native/local-submission.ts";
import { isNativeRuntime } from "./native/runtime.ts";

/**
 * Phase 2F — durable, native-first local working-submission storage.
 *
 * This is deliberately NOT a replacement for any existing web/PWA draft
 * mechanism (lib/offline-job-card-drafts.ts's IndexedDB store, the
 * localStorage interval autosave, or the online-only job_card_drafts Cloud
 * Draft) — all three continue exactly as before. This repository exists
 * because NONE of those give native (Capacitor/Android) a real, durable,
 * properly (userId, projectId)-scoped storage boundary: today even
 * "Save to this device" on native writes into the WebView's own embedded
 * IndexedDB, never the app's native SQLite database every other Phase
 * 2B-2E repository uses. See lib/native/local-submission.ts's own doc for
 * the schema.
 *
 * `payload` is intentionally generic (`TPayload`) rather than importing
 * components/NewSubmissionForm.tsx's StoredJobCardDraft type here — lib/
 * must not depend on components/ (the dependency runs the other way
 * everywhere else in this codebase). The caller (NewSubmissionForm.tsx)
 * supplies and reads back its own concrete payload shape.
 *
 * Identity: `localSubmissionId` is generated by the CALLER (the existing
 * generateSubmissionId()/generateId() already used for CoreJobFields'
 * submissionId — see NewSubmissionForm.tsx) — it is the SAME id, not a
 * third parallel one, and is already what job_card_submissions.submission_id
 * uses as its idempotency key once a submission eventually syncs. This
 * repository never generates or mutates that id itself.
 */
/**
 * "working": the default — still being edited, or nothing has explicitly
 * marked it done yet.
 *
 * "locally-complete": the technician has passed the SAME full validation
 * gate (collectReviewValidationIssues() in NewSubmissionForm.tsx) the
 * online path already requires to reach Review — every required
 * core/vehicle/product field, every required photo slot has at least one
 * locally-selected file — and the local record is ready for a FUTURE sync
 * phase to pick up. It is NOT, and must never be read as, "submitted" or
 * "accepted by the server" — Phase 2F implements no sync/outbox at all;
 * `serverSubmissionId` stays null regardless of this status. See
 * NewSubmissionForm.tsx's handleReviewClick for the exact transition and
 * its own caveat about photo File selections not surviving a restart even
 * though this status does.
 */
export type LocalSubmissionStatus = "working" | "locally-complete";

export type LocalSubmission<TPayload = unknown> = {
  localSubmissionId: string;
  userId: string;
  projectId: string;
  companyId: string;
  status: LocalSubmissionStatus;
  /** Registry form id when known — identity of the product/config this submission was created against. */
  formId: string | null;
  submissionType: string | null;
  /**
   * Set exactly once, ONLY by the atomic Phase 2H technician-submit
   * transaction (see lib/local-submission-outbox.ts's
   * technicianSubmitAtomically) — never by saveLocalSubmission, which never
   * reads or writes this column (see its own native upsert SQL: this
   * column is deliberately omitted from both the INSERT column list and
   * the ON CONFLICT DO UPDATE SET clause, the same preserve-on-conflict
   * trick already used for createdAt). null means "still Working/Draft, not
   * yet submitted" — see findUnsubmittedLocalSubmissions below, and Phase
   * 2H's own Saved-vs-Submitted classification doc. Deliberately distinct
   * from `status` ("locally-complete" is a pure editing-progress concept
   * and must never be read as submitted — see that field's own doc).
   */
  technicianSubmittedAt: string | null;
  /**
   * The CompanyProductDefinitionsPackage/ProjectWorkPackage schema version
   * in effect when this submission was created — recorded for diagnostic
   * purposes only. Phase 2F does not implement definition-version
   * migration: a resumed submission always keeps showing its own entered
   * values regardless of what this says: see this module's doc on prefill
   * boundaries.
   */
  definitionSchemaVersion: number | null;
  selectedSections: string[];
  /** The technician's structured work — never photo/file Blob bytes; see NewSubmissionForm.tsx's own photo-state boundary. */
  payload: TPayload;
  /** Always null in Phase 2F — populated only once a future sync/outbox phase exists. */
  serverSubmissionId: string | null;
  /** Set once, on first write, and never changed by later saves (see repository doc). */
  createdAt: string;
  updatedAt: string;
};

/**
 * technicianSubmittedAt is deliberately excluded here too — saveLocalSubmission
 * (the ordinary autosave/working-save path) never sets it; see that field's own doc.
 */
export type LocalSubmissionInput<TPayload = unknown> = Omit<
  LocalSubmission<TPayload>,
  "createdAt" | "updatedAt" | "technicianSubmittedAt"
>;

export interface LocalSubmissionRepository {
  /**
   * Upserts by localSubmissionId. `createdAt` is preserved from the
   * original write for an existing row (never reset on later saves) —
   * see the native/web implementations' own upsert logic. Resolves with
   * the updatedAt actually committed. Rejects, leaving any previous row
   * for this exact localSubmissionId fully intact, if the write fails —
   * a caller must never treat a rejection as "the prior save is gone."
   */
  saveLocalSubmission<TPayload>(input: LocalSubmissionInput<TPayload>): Promise<{ updatedAt: string }>;
  loadLocalSubmission<TPayload>(localSubmissionId: string): Promise<LocalSubmission<TPayload> | null>;
  /**
   * The resume-detection query: every `status: "working"` submission for
   * this exact (userId, projectId), newest-updated first. A row whose
   * payload fails to parse is skipped (not thrown) so one corrupted
   * submission never hides every other resumable one from the picker —
   * contrast with loadLocalSubmission's throw-on-malformed behavior, which
   * is correct there because that call has no other candidate to fall
   * back to.
   */
  findWorkingLocalSubmissions<TPayload>(userId: string, projectId: string): Promise<LocalSubmission<TPayload>[]>;
  /**
   * Phase 2H — the corrected resume-detection query: every submission for
   * this exact (userId, projectId) with technician_submitted_at IS NULL,
   * newest-updated first, REGARDLESS of `status` (working OR
   * locally-complete). Deliberately NOT `findWorkingLocalSubmissions` with
   * an added filter — a "locally-complete" submission the technician has
   * NOT yet explicitly submitted must still be resumable/visible here (see
   * Phase 2H's design-review correction on this exact point). Same
   * malformed-row skip behavior as findWorkingLocalSubmissions.
   */
  findUnsubmittedLocalSubmissions<TPayload>(userId: string, projectId: string): Promise<LocalSubmission<TPayload>[]>;
  /**
   * Narrow, single-column write: records the server's confirmed identity
   * once Phase 2H's finalize call has succeeded. Never touches status,
   * technician_submitted_at, or payload — those are owned by the technician-
   * submit transaction and the ordinary save path respectively.
   */
  recordServerConfirmation(localSubmissionId: string, serverSubmissionId: string): Promise<void>;
  deleteLocalSubmission(localSubmissionId: string): Promise<void>;
}

/**
 * Phase 2F is native-only in its actual integration (NewSubmissionForm.tsx
 * only ever calls this repository on the authoritative isOfflineAuthorized
 * branch, which can itself never be true on web — see
 * lib/auth/auth-state.ts). Web keeps its existing IndexedDB/localStorage
 * draft mechanisms entirely unchanged and untouched. Mirrors
 * lib/native/database.ts's WebDatabaseNotImplemented exactly: a throwing
 * placeholder so the interface stays whole and testable without giving web
 * a second, redundant, never-actually-used draft store.
 */
const WEB_NOT_IMPLEMENTED_MESSAGE =
  "Local submission storage is not implemented for the web runtime. The web app continues to use lib/offline-job-card-drafts.ts (IndexedDB) and the localStorage autosave directly.";

class WebLocalSubmissionNotImplemented implements LocalSubmissionRepository {
  saveLocalSubmission<TPayload>(): Promise<{ updatedAt: string }> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  loadLocalSubmission<TPayload>(): Promise<LocalSubmission<TPayload> | null> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  findWorkingLocalSubmissions<TPayload>(): Promise<LocalSubmission<TPayload>[]> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  findUnsubmittedLocalSubmissions<TPayload>(): Promise<LocalSubmission<TPayload>[]> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  recordServerConfirmation(): Promise<void> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  deleteLocalSubmission(): Promise<void> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
}

const webLocalSubmissionSingleton = new WebLocalSubmissionNotImplemented();

export function getLocalSubmissionRepository(): LocalSubmissionRepository {
  return isNativeRuntime() ? getNativeLocalSubmission() : webLocalSubmissionSingleton;
}

export type DeleteLocalSubmissionDurablyDeps = {
  submissionRepo: Pick<LocalSubmissionRepository, "deleteLocalSubmission">;
  photoMetadataRepo: Pick<LocalPhotoMetadataRepository, "listLocalPhotosForSubmission">;
  deletePhotoDurably: (localPhotoId: string) => Promise<void>;
};

/**
 * The ONE place a LocalSubmission and everything durably associated with it
 * (LocalPhoto metadata rows + their filesystem bytes, via the existing
 * deleteLocalPhotoDurably) gets removed together — used by both
 * SavedJobCardsScreen.tsx's explicit Delete action and
 * NewSubmissionForm.tsx's Exit-Without-Saving-on-a-brand-new-draft path (see
 * that file's own doc on why only a session-created draft, never a resumed
 * one, is ever discarded this way). Photos are deleted BEFORE the
 * submission row so a failure partway through never leaves the submission
 * gone while photo metadata still claims to belong to it.
 */
export async function deleteLocalSubmissionDurably(
  localSubmissionId: string,
  deps: DeleteLocalSubmissionDurablyDeps = {
    submissionRepo: getLocalSubmissionRepository(),
    photoMetadataRepo: getLocalPhotoMetadataRepository(),
    deletePhotoDurably: deleteLocalPhotoDurably,
  },
): Promise<void> {
  const photos = await deps.photoMetadataRepo.listLocalPhotosForSubmission(localSubmissionId);
  for (const photo of photos) {
    await deps.deletePhotoDurably(photo.localPhotoId);
  }
  await deps.submissionRepo.deleteLocalSubmission(localSubmissionId);
}

export type LocalSubmissionResumeOutcome<TPayload = unknown> =
  | { kind: "none" }
  | { kind: "single"; submission: LocalSubmission<TPayload> }
  | { kind: "multiple"; submissions: LocalSubmission<TPayload>[] };

/**
 * Pure — decides what the "Start New Submission" entry point should show
 * given whatever findWorkingLocalSubmissions() returned for this exact
 * (userId, projectId). Unit-testable without any SQLite I/O — see
 * local-submission.test.ts. Ordering is whatever the repository already
 * returned (newest-updated first); this function does not re-sort.
 */
export function resolveLocalSubmissionResumeOutcome<TPayload>(
  working: readonly LocalSubmission<TPayload>[],
): LocalSubmissionResumeOutcome<TPayload> {
  if (working.length === 0) return { kind: "none" };
  if (working.length === 1) return { kind: "single", submission: working[0] };
  return { kind: "multiple", submissions: [...working] };
}
