import { getNativeLocalSubmission } from "./native/local-submission.ts";
import { isNativeRuntime } from "./native/runtime.ts";

/**
 * Phase 2F — durable, native-first local working-submission storage.
 *
 * This is deliberately NOT a replacement for any existing web/PWA draft
 * mechanism (lib/offline-job-card-drafts.ts's IndexedDB store, the
 * localStorage interval autosave, or the online-only job_card_drafts Cloud
 * Draft) — all three continue exactly as before. This repository exists
 * because NONE of those give native (Capacitor/Android) a real, durable,
 * properly (userId, projectId)-scoped storage boundary: today even
 * "Save to this device" on native writes into the WebView's own embedded
 * IndexedDB, never the app's native SQLite database every other Phase
 * 2B-2E repository uses. See lib/native/local-submission.ts's own doc for
 * the schema.
 *
 * `payload` is intentionally generic (`TPayload`) rather than importing
 * components/NewSubmissionForm.tsx's StoredJobCardDraft type here — lib/
 * must not depend on components/ (the dependency runs the other way
 * everywhere else in this codebase). The caller (NewSubmissionForm.tsx)
 * supplies and reads back its own concrete payload shape.
 *
 * Identity: `localSubmissionId` is generated by the CALLER (the existing
 * generateSubmissionId()/generateId() already used for CoreJobFields'
 * submissionId — see NewSubmissionForm.tsx) — it is the SAME id, not a
 * third parallel one, and is already what job_card_submissions.submission_id
 * uses as its idempotency key once a submission eventually syncs. This
 * repository never generates or mutates that id itself.
 */
/**
 * "working": the default — still being edited, or nothing has explicitly
 * marked it done yet.
 *
 * "locally-complete": the technician has passed the SAME full validation
 * gate (collectReviewValidationIssues() in NewSubmissionForm.tsx) the
 * online path already requires to reach Review — every required
 * core/vehicle/product field, every required photo slot has at least one
 * locally-selected file — and the local record is ready for a FUTURE sync
 * phase to pick up. It is NOT, and must never be read as, "submitted" or
 * "accepted by the server" — Phase 2F implements no sync/outbox at all;
 * `serverSubmissionId` stays null regardless of this status. See
 * NewSubmissionForm.tsx's handleReviewClick for the exact transition and
 * its own caveat about photo File selections not surviving a restart even
 * though this status does.
 */
export type LocalSubmissionStatus = "working" | "locally-complete";

export type LocalSubmission<TPayload = unknown> = {
  localSubmissionId: string;
  userId: string;
  projectId: string;
  companyId: string;
  status: LocalSubmissionStatus;
  /** Registry form id when known — identity of the product/config this submission was created against. */
  formId: string | null;
  submissionType: string | null;
  /**
   * The CompanyProductDefinitionsPackage/ProjectWorkPackage schema version
   * in effect when this submission was created — recorded for diagnostic
   * purposes only. Phase 2F does not implement definition-version
   * migration: a resumed submission always keeps showing its own entered
   * values regardless of what this says: see this module's doc on prefill
   * boundaries.
   */
  definitionSchemaVersion: number | null;
  selectedSections: string[];
  /** The technician's structured work — never photo/file Blob bytes; see NewSubmissionForm.tsx's own photo-state boundary. */
  payload: TPayload;
  /** Always null in Phase 2F — populated only once a future sync/outbox phase exists. */
  serverSubmissionId: string | null;
  /** Set once, on first write, and never changed by later saves (see repository doc). */
  createdAt: string;
  updatedAt: string;
};

export type LocalSubmissionInput<TPayload = unknown> = Omit<LocalSubmission<TPayload>, "createdAt" | "updatedAt">;

export interface LocalSubmissionRepository {
  /**
   * Upserts by localSubmissionId. `createdAt` is preserved from the
   * original write for an existing row (never reset on later saves) —
   * see the native/web implementations' own upsert logic. Resolves with
   * the updatedAt actually committed. Rejects, leaving any previous row
   * for this exact localSubmissionId fully intact, if the write fails —
   * a caller must never treat a rejection as "the prior save is gone."
   */
  saveLocalSubmission<TPayload>(input: LocalSubmissionInput<TPayload>): Promise<{ updatedAt: string }>;
  loadLocalSubmission<TPayload>(localSubmissionId: string): Promise<LocalSubmission<TPayload> | null>;
  /**
   * The resume-detection query: every `status: "working"` submission for
   * this exact (userId, projectId), newest-updated first. A row whose
   * payload fails to parse is skipped (not thrown) so one corrupted
   * submission never hides every other resumable one from the picker —
   * contrast with loadLocalSubmission's throw-on-malformed behavior, which
   * is correct there because that call has no other candidate to fall
   * back to.
   */
  findWorkingLocalSubmissions<TPayload>(userId: string, projectId: string): Promise<LocalSubmission<TPayload>[]>;
  deleteLocalSubmission(localSubmissionId: string): Promise<void>;
}

/**
 * Phase 2F is native-only in its actual integration (NewSubmissionForm.tsx
 * only ever calls this repository on the authoritative isOfflineAuthorized
 * branch, which can itself never be true on web — see
 * lib/auth/auth-state.ts). Web keeps its existing IndexedDB/localStorage
 * draft mechanisms entirely unchanged and untouched. Mirrors
 * lib/native/database.ts's WebDatabaseNotImplemented exactly: a throwing
 * placeholder so the interface stays whole and testable without giving web
 * a second, redundant, never-actually-used draft store.
 */
const WEB_NOT_IMPLEMENTED_MESSAGE =
  "Local submission storage is not implemented for the web runtime. The web app continues to use lib/offline-job-card-drafts.ts (IndexedDB) and the localStorage autosave directly.";

class WebLocalSubmissionNotImplemented implements LocalSubmissionRepository {
  saveLocalSubmission<TPayload>(): Promise<{ updatedAt: string }> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  loadLocalSubmission<TPayload>(): Promise<LocalSubmission<TPayload> | null> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  findWorkingLocalSubmissions<TPayload>(): Promise<LocalSubmission<TPayload>[]> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
  deleteLocalSubmission(): Promise<void> {
    throw new Error(WEB_NOT_IMPLEMENTED_MESSAGE);
  }
}

const webLocalSubmissionSingleton = new WebLocalSubmissionNotImplemented();

export function getLocalSubmissionRepository(): LocalSubmissionRepository {
  return isNativeRuntime() ? getNativeLocalSubmission() : webLocalSubmissionSingleton;
}

export type LocalSubmissionResumeOutcome<TPayload = unknown> =
  | { kind: "none" }
  | { kind: "single"; submission: LocalSubmission<TPayload> }
  | { kind: "multiple"; submissions: LocalSubmission<TPayload>[] };

/**
 * Pure — decides what the "Start New Submission" entry point should show
 * given whatever findWorkingLocalSubmissions() returned for this exact
 * (userId, projectId). Unit-testable without any SQLite I/O — see
 * local-submission.test.ts. Ordering is whatever the repository already
 * returned (newest-updated first); this function does not re-sort.
 */
export function resolveLocalSubmissionResumeOutcome<TPayload>(
  working: readonly LocalSubmission<TPayload>[],
): LocalSubmissionResumeOutcome<TPayload> {
  if (working.length === 0) return { kind: "none" };
  if (working.length === 1) return { kind: "single", submission: working[0] };
  return { kind: "multiple", submissions: [...working] };
}
